### ISSUE TITLE
Swagger connector requires undocumented uri option

### ISSUE THREAD

**Issue by Blackbaud-ChristineViets** [appcelerator/appc.swagger#1]
[http://software.appcelerator.com/detail/connector/appc.swagger@1.0.16](http://software.appcelerator.com/detail/connector/appc.swagger@1.0.16) and this github have no information on how to get started other then using `appc install`, so I assumed it would work/guide out of the box.

After install it gave some useful info:

~~~
connector/appc.swagger provided a default configuration example which was written to conf/appc.swagger.default.js
You must update the config file located in /Users/fokkezb/dev/appcelerator/appc-devlink-server/conf/appc.swagger.default.js before you can use it!
~~~

I had the Arrow app running in another terminal session so it restarted because it saw changes, but a fresh `appc run` gave me the same result:

~~~
Restarting due to changes to:
 
	/Users/fokkezb/dev/appcelerator/appc-devlink-server/conf/appc.swagger.default.js
 
 
INFO   | Arrow/1.2.62 DevLink/1.0.19
INFO   | APIKey is: d5GjQDD5yE7DAvZ1FhUyIoHThRBwTlkt
INFO   | starting connector/appc.swagger@1.0.16
ERROR  | Login failed. Please double check your credentials.
Uncaught Exception Error loading connector/appc.swagger. Error loading connector/appc.swagger. options.uri is a required argument
Error: Error loading connector/appc.swagger. Error loading connector/appc.swagger. options.uri is a required argument
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/lib/arrow.js:513:11
    at Connector.connectCallback (/Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/lib/connector.js:464:21)
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:251:17
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:148:21
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:248:21
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:612:34
    at Connector.connectTask (/Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/lib/connector.js:428:5)
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:607:21
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:246:17
    at iterate (/Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:146:13)
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:157:25
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:248:21
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:612:34
    at Connector.configTask (/Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/lib/connector.js:418:5)
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:607:21
    at /Users/fokkezb/.appcelerator/install/5.0.4/package/node_modules/arrow/node_modules/arrow-orm/node_modules/async/lib/async.js:246:17
~~~

I opened `conf/appc.swagger.default.js` to look for an uri option, but there was not.
No idea how to continue from here.

This has been [filed](https://jira.appcelerator.org/browse/API-1119) on Appcelerator's JIRA dashboard as well.

**Comment by FokkeZB** [comment]
This is a 1:1 copy of this JIRA ticket I created a few months ago:
https://jira.appcelerator.org/browse/API-1119
